# file: mysql/tasks/main.yml

- include: install.yml
  when: mysql_install_package == 'default'
- include: percona.yml
  when: mysql_install_package == 'percona'
- include: configure.yml
- include: secure.yml
- include: databases.yml
- include: users.yml
- include: monit.yml
  when: monit_protection is defined and monit_protection == true
